services:
  strawberry-fastapi:
    image: strawberry-fastapi
    build: .
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    entrypoint: pdm dev --host 0.0.0.0 --port $$PORT
    healthcheck:
      test: curl -f http://localhost:$$PORT/?query=%7B__typename%7D || exit 1
      interval: 3s
      timeout: 1s
